[package]
name = "file_server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio-util = { version = "0.7", features = ["io"] }
mime_guess = "2.0.5"
axum = "0.6.20"
tokio = { version = "1.32.0", features = ["full"] }